### ISSUE TITLE
Failing Search

### ISSUE THREAD

**Issue by iogbole** [rundocs/jekyll-rtd-theme#11]
@saowang it might be worth taking a closer look at the search. I have had my site up for nearly a day and it's still not returning any search result. Is it expected? Should it be on by default? 

You may test with 
https://appdynamics.github.io/ConfigMyApp/

**Comment by saowang** [comment]
Thank you very much for your suggestion. After careful inspection, there is indeed a major BUG, because there is an error caused by the backslash in your document. Now the search data is generated perfectly (in a native way), and you can search now, but the previous js It needs to be optimized, thank you very much!

**Comment by iogbole** [comment]
Thanks for fixing this, @saowang . It is returning results now but could be better. It seems to be case sensitive. For example, search for `jenkins` returns no result, but `Jenkins`  returns a result. Is this expected?
