### ISSUE TITLE
All customisations are gone... 

### ISSUE THREAD

**Issue by iogbole** [rundocs/jekyll-rtd-theme#42]
All the customisations on the site have disappeared. Something else changed?  @saowang

**Comment by saowang** [comment]
Version 2.0 have refactored the original theme based on GitHub `@primer/css`, Can still be customized, but now more flexible!

Many customized changes have been repealed, because it will cause confusion for many users


I think you just changed the sidebar background, you can overwrite the scss variable file to see the powerful structure

https://github.com/rundocs/jekyll-rtd-theme/blob/master/_sass/_variables.scss

**Comment by saowang** [comment]
https://github.com/rundocs/jekyll-rtd-theme/tree/v1

```
remote_theme: rundocs/jekyll-rtd-theme@v1
```

**Comment by stain** [comment]
I like the new customization options, although I could not get them to work..

I've tried copying over ` _sass/_variables.scss` to my `docs/_sass/` but nothing seems to be picked up. Which folder does it need to be placed in? If I modify `custom.scss` I don't seem to have access to the variables.

**Comment by saowang** [comment]
Hello there!  Since the version released through CDN is used by default, all the coverage of the _sass folder cannot be reflected. You need to turn on the debug mode to use the non-cdn dynamic build style. In addition, custom.scss cannot be used in the _sass folder  The set variable is indeed a loophole and needs improvement!
