### ISSUE TITLE
Custom CSS and SCSS no longer override theme

### ISSUE THREAD

**Issue by Aidenjn** [rundocs/jekyll-rtd-theme#84]
**Describe the BUG**
Custom CSS and SCSS no longer overrides the theme's.
I had some custom CSS and SCSS inside of the _includes/assets folder of my [repository](https://github.com/Aidenjn/bogl-docs) that affected the site. It worked well up until a day or two ago. I did not make any changes to my code during this time.

**To Reproduce**
Try overriding the theme's styling with a .scss file as per instructed in the [documentation](https://rundocs.io/configuring/custom.html).

**Site link or Repository**
https://github.com/Aidenjn/bogl-docs

**Comment by saowang** [comment]
Hello friends, since the custom scss cannot use the default variables of the theme well (but you can still import them), in view of this, change the custom folder to an extra folder.

You can still custom
```yml
scss:   # also _includes/extra/styles.scss
script: # also _includes/extra/script.js
```

For more details see https://github.com/rundocs/jekyll-rtd-theme/tree/develop/_includes/extra

**Comment by jrfnl** [comment]
Was just looking for a solution to this as it wasn't working for me either. Glad to have found it.
